import type { User, Video } from '../types';

export const initialUsers: User[] = [
  {
    id: 'admin_1',
    name: 'Santosh Kumar',
    email: 'admin@srividyabharathi.com',
    password: '1234@Santosh',
    type: 'admin',
    status: 'active',
  },
  {
    id: 'student_1',
    name: 'Arjun Sharma',
    email: 'arjun@example.com',
    password: 'password123',
    type: 'student',
    class: '10',
    status: 'active',
  },
  {
    id: 'student_2',
    name: 'Priya Patel',
    email: 'priya@example.com',
    password: 'password123',
    type: 'student',
    class: '9',
    status: 'active',
  },
  {
    id: 'student_3',
    name: 'Rohan Mehta',
    email: 'rohan@example.com',
    password: 'password123',
    type: 'student',
    class: '8',
    status: 'disabled',
  },
   {
    id: 'student_4',
    name: 'Sneha Verma',
    email: 'sneha@example.com',
    password: 'password123',
    type: 'student',
    class: '10',
    status: 'active',
  },
];

export const initialVideos: Video[] = [
    {
        id: 'vid_1',
        title: 'Introduction to Algebra',
        description: 'Learn the basics of algebraic expressions and equations.',
        subject: 'Mathematics',
        class: '8',
        duration: '18:45',
        views: 1250,
        status: 'published',
        thumbnailUrl: 'https://placehold.co/600x400/3B82F6/FFF?text=EduPortal+Video',
        videoUrls: {
            '1080p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
            '720p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
            '480p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        },
        uploadedAt: '2023-10-26T10:00:00Z',
    },
    {
        id: 'vid_2',
        title: 'The Cell: Basic Unit of Life',
        description: 'Explore the structure and function of a biological cell.',
        subject: 'Science',
        class: '9',
        duration: '22:10',
        views: 2345,
        status: 'published',
        thumbnailUrl: 'https://placehold.co/600x400/3B82F6/FFF?text=EduPortal+Video',
        videoUrls: {
            '1080p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
            '720p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        },
        uploadedAt: '2023-10-25T11:30:00Z',
    },
    {
        id: 'vid_3',
        title: 'Indian Independence Movement',
        description: 'A deep dive into the history of India\'s struggle for freedom.',
        subject: 'History',
        class: '10',
        duration: '35:50',
        views: 3100,
        status: 'published',
        thumbnailUrl: 'https://placehold.co/600x400/3B82F6/FFF?text=EduPortal+Video',
        videoUrls: {
            '720p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        },
        uploadedAt: '2023-10-24T09:00:00Z',
    },
    {
        id: 'vid_4',
        title: 'Shakespeare\'s Sonnets',
        description: 'An analysis of the most famous sonnets by William Shakespeare.',
        subject: 'English',
        class: '10',
        duration: '15:20',
        views: 980,
        status: 'draft',
        thumbnailUrl: 'https://placehold.co/600x400/3B82F6/FFF?text=EduPortal+Video',
        videoUrls: {
            '720p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        },
        uploadedAt: '2023-10-23T14:00:00Z',
    },
    {
        id: 'vid_5',
        title: 'Newton\'s Laws of Motion',
        description: 'Understanding the fundamental principles of motion.',
        subject: 'Physics',
        class: '9',
        duration: '28:05',
        views: 1850,
        status: 'published',
        thumbnailUrl: 'https://placehold.co/600x400/3B82F6/FFF?text=EduPortal+Video',
        videoUrls: {
            '1080p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
            '720p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        },
        uploadedAt: '2023-10-22T16:45:00Z',
    },
    {
        id: 'vid_6',
        title: 'World Geography: Continents',
        description: 'An overview of the world\'s continents and oceans.',
        subject: 'Geography',
        class: '8',
        duration: '20:00',
        views: 750,
        status: 'published',
        thumbnailUrl: 'https://placehold.co/600x400/3B82F6/FFF?text=EduPortal+Video',
        videoUrls: {
            '720p': 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
        },
        uploadedAt: '2023-10-21T10:15:00Z',
    },
];